### ISSUE TITLE
gulp --target=nRF51-DK error

### ISSUE THREAD

**Issue by pmcalabrese** [ARMmbed/mbed-js-example#2]
After following the installing instructions,
I try to run

`gulp --target=nRF51-DK`

and i get the following error

```
[21:36:39] Finished 'bundle' after 132 ms
[21:36:39] 'getlibs' errored after 157 ms
[21:36:39] Error: Command `make getlibs` exited with code 2
    at ChildProcess.handleSubShellExit (/Users/mca/dev/mbed-js-example/node_modules/gulp-run/command.js:166:13)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
$ make getlibs
[mbed] ERROR: Could not find mbed program in current path "/Users/mca/dev/mbed-js-example/build/jerryscript/targets/mbedos5".
[mbed] ERROR: Change the current directory to a valid mbed program or use the '--global' option to set global configuration.
---
mbed config root .
[mbed] ERROR: Could not find mbed program in current path "/Users/mca/dev/mbed-js-example/build/jerryscript/targets/mbedos5".
[mbed] ERROR: Change the current directory to a valid mbed program or use the '--global' option to set global configuration.
---
make: *** [.mbed] Error 255
```

any suggestions would be much appreciated?

Thanks

**Comment by matthewelse** [comment]
@pmcalabrese sorry for the delay - have you tried `gulp --target=NRF51_DK` - I think the mbed build tools expect the target name to be formatted in a specific way.

Additionally (I might be wrong, @janjongboom will know) - I don't think we've successfully run JavaScript on mbed with the NRF51 DK yet (either not enough RAM or Flash I can't remember), you might have more luck if you can get hold of an NRF52 board (that will then be `gulp --target=NRF52_DK`)

**Comment by janjongboom** [comment]
@pmcalabrese What Matthew says. Anyway, the nRF51-DK is not supported as it does not have 64K of RAM (minimum required for JS on mbed).

**Comment by pmcalabrese** [comment]
@matthewelse and @janjongboom Thanks for your support. OK, I'll grub a nrf52 dev board. But I still get the following error. I believe is some miss configuration.

```
[10:20:48] Error: Command `make getlibs` exited with code 2
    at ChildProcess.handleSubShellExit (/Users/mca/dev/mbed-js-example/node_modules/gulp-run/command.js:166:13)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
$ make getlibs
[mbed] ERROR: Could not find mbed program in current path "/Users/mca/dev/mbed-js-example/build/jerryscript/targets/mbedos5".
[mbed] ERROR: Change the current directory to a valid mbed program or use the '--global' option to set global configuration.
---
mbed config root .
[mbed] ERROR: Could not find mbed program in current path "/Users/mca/dev/mbed-js-example/build/jerryscript/targets/mbedos5".
[mbed] ERROR: Change the current directory to a valid mbed program or use the '--global' option to set global configuration.
---
make: *** [.mbed] Error 255
```

Am I missing something?

**Comment by janjongboom** [comment]
@pmcalabrese Interesting error... I re-cloned this project and didn't run into this, although I needed jerryscript-project/jerryscript#1485 (but seems unrelated).

Some sanity checks, do you have the following installed?

- Git
- ARM Cross-compiler (arm-non-eabi-gcc should be in your path)
- mbed CLI

If not, is there an error above this that shows more info?

**Comment by pmcalabrese** [comment]
Thanks @janjongboom , i did some progress. I have installed ARM Cross-compiler (`brew install arm-none-eabi-gcc
 `), mbed CLI (I already have Git) and Mercurial which is a dependency of mbed CLI. Now i'm closer to the compilation, but i get another error... maybe you can give some more hints:

when I try to run

`gulp --target=NRF52_DK`

i get

```
Compile: ecma-helpers-external-pointers.c
Compile: ecma-alloc.c
Compile: ecma-helpers-values-collection.c
Compile: ecma-helpers-errol.c
Compile: ecma-init-finalize.c
Compile: ecma-builtin-arraybuffer-prototype.c
[Warning] ecma-arraybuffer-object.h@37,1: always_inline function might not be inlinable [-Wattributes]
[Warning] ecma-arraybuffer-object.h@39,1: always_inline function might not be inlinable [-Wattributes]
[Error] ecma-arraybuffer-object.h@39,0: inlining failed in call to always_inline 'ecma_arraybuffer_get_length': function body not available
[Error] ecma-builtin-arraybuffer-prototype.c@64,21: called from here
[ERROR] In file included from ../../jerry-core/ecma/builtin-objects/ecma-builtin-arraybuffer-prototype.c:22:0:
../../jerry-core/ecma/operations/ecma-arraybuffer-object.h:37:1: warning: always_inline function might not be inlinable [-Wattributes]
 ecma_arraybuffer_get_buffer (ecma_object_t *) __attr_pure___ __attr_always_inline___;
 ^
../../jerry-core/ecma/operations/ecma-arraybuffer-object.h:39:1: warning: always_inline function might not be inlinable [-Wattributes]
 ecma_arraybuffer_get_length (ecma_object_t *) __attr_pure___ __attr_always_inline___;
 ^
../../jerry-core/ecma/builtin-objects/ecma-builtin-arraybuffer-prototype.c: In function 'ecma_builtin_arraybuffer_prototype_bytelength_getter':
../../jerry-core/ecma/operations/ecma-arraybuffer-object.h:39:1: error: inlining failed in call to always_inline 'ecma_arraybuffer_get_length': function body not available
../../jerry-core/ecma/builtin-objects/ecma-builtin-arraybuffer-prototype.c:64:21: error: called from here
       ecma_length_t len = ecma_arraybuffer_get_length (object_p);
                     ^

[mbed] ERROR: "python" returned error code 1.
[mbed] ERROR: Command "python -u /Users/mca/dev/mbed-js-example/.temp/tools/make.py -t GCC_ARM -m NRF52_DK --source . --source ../../ --source ../../../source --build ../../../out/NRF52_DK -j0 -D CONFIG_MEM_HEAP_AREA_SIZE=(1024*16)" in "/Users/mca/dev/mbed-js-example/build/jerryscript/targets/mbedos5"
---
make[1]: *** [all] Error 1
make: *** [all] Error 2
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Command `make BOARD=NRF52_DK EXTRAS=` exited with code 2
    at ChildProcess.handleSubShellExit (/Users/mca/dev/mbed-js-example/node_modules/gulp-run/command.js:166:13)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

Thanks again

**Comment by janjongboom** [comment]
Hi @pmcalabrese, Yep that looks better. We fixed this yesterday by pinning mbed-js-gulp to a specific version of JerryScript (and it's fixed upstream in https://github.com/jerryscript-project/jerryscript/pull/1485):

1. Run `npm update`.
1. Remove the `build` folder.
1. Run gulp again.

Build should complete.

**Comment by pmcalabrese** [comment]
Hi @janjongboom. It compiles, thanks for your help!

*On OSX*

What I've done is
- Install ARM Cross-compiler with brew
```
brew install arm-none-eabi-gcc
```
- Install Mercurial from [https://www.mercurial-scm.org/downloads](https://www.mercurial-scm.org/downloads)
- Install mbed CLI, very good docs here -> [https://github.com/ARMmbed/mbed-cli#installing-mbed-cli](https://github.com/ARMmbed/mbed-cli#installing-mbed-cli)

I already had git, python and node installed. Hope this can be informative.

**Comment by janjongboom** [comment]
@pmcalabrese Great, thanks! We'll release installers for Windows and macOS for mbed CLI soon, which should solve most of these problems.

**Comment by pmcalabrese** [comment]
@janjongboom after updating i still get this error

```
Error: Command `make BOARD=NRF52_DK EXTRAS=` exited with code 2
```

any suggestions?

**Comment by janjongboom** [comment]
@pmcalabrese Can you give the full log - perhaps in a gist?

**Comment by pmcalabrese** [comment]
@janjongboom there you go

https://gist.github.com/pmcalabrese/249a7de04b9e99dc13a4d71b43196a4c

**Comment by janjongboom** [comment]
@pmcalabrese Which version of mbed CLI are you running (`mbed --version`)?

I'm on mbed CLI 1.0.0 and it compiles for me... (when I manually patch in https://github.com/jerryscript-project/jerryscript/pull/1512, as I didn't upstream it yet in mbed-js-gulp).

**Comment by janjongboom** [comment]
FYI, patched mbed-js-gulp in [this commit](https://github.com/ARMmbed/mbed-js-gulp/pull/13) which points to a newer JerryScript version.

**Comment by pmcalabrese** [comment]
I'm on mbed 1.0.0 as well. Maybe I should patch...

**Comment by pmcalabrese** [comment]
By patching and deleting the `.temp` folder. everything work as expected. Thanks

**Comment by janjongboom** [comment]
@pmcalabrese Great, hope to land it tomorrow when the EU wakes up.

**Comment by solancer** [comment]
The item “mbedos5.hex” can’t be copied because there isn’t enough free space. The hex file is about 1.2MB in size!

**Comment by pmcalabrese** [comment]
I had the same problem. It's important that you use the ARM  boatloader and not the mbed one.

**Comment by janjongboom** [comment]
@solancer ^
